"""feat: Adicioando novos campos de empretimos.

Revision ID: 2e3f519bf288
Revises: bf73ea9c46a8
Create Date: 2026-09-21 17:33:40.219979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e3f519bf288'
down_revision: Union[str, Sequence[str], None] = 'bf73ea9c46a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emprestimos', sa.Column('ativo', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emprestimos', 'ativo')
    # ### end Alembic commands ###
