"""feat: Adicioando o cascade na foreingkey de livros_id da tabela emprestimos para sempre que um livro ser apagado deletar os emprestimos.

Revision ID: 3d83cca4f19a
Revises: 2e3f519bf288
Create Date: 2026-09-23 15:27:23.996043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d83cca4f19a'
down_revision: Union[str, Sequence[str], None] = '2e3f519bf288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('emprestimos_livros_id_fkey'), 'emprestimos', type_='foreignkey')
    op.create_foreign_key(None, 'emprestimos', 'livros', ['livros_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'emprestimos', type_='foreignkey')
    op.create_foreign_key(op.f('emprestimos_livros_id_fkey'), 'emprestimos', 'livros', ['livros_id'], ['id'])
    # ### end Alembic commands ###
