"""adicionando o campo de credenciais a tabela de users

Revision ID: 451a530489f4
Revises: 3c6700fb903a
Create Date: 2026-09-14 17:44:48.464499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '451a530489f4'
down_revision: Union[str, Sequence[str], None] = '3c6700fb903a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('credenciais', sa.String(), server_default='User', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'credenciais')
    # ### end Alembic commands ###
