"""feat: Criando a tabela de emprestimos e adicionando os campos nas outras tabelas para fazer referencias

Revision ID: 7b318d0babc4
Revises: e3975ba804c0
Create Date: 2026-09-21 15:18:34.668971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b318d0babc4'
down_revision: Union[str, Sequence[str], None] = 'e3975ba804c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('livros_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livros_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('livros', sa.Column('estoque', sa.Integer(), nullable=False))
    op.drop_column('livros', 'author')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('livros', sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('livros', 'estoque')
    op.drop_table('emprestimos')
    # ### end Alembic commands ###
