"""Alterando a campo de credenciais para boleando e mudando seu nome

Revision ID: be0ce7b08fda
Revises: 451a530489f4
Create Date: 2026-09-16 14:52:24.618174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be0ce7b08fda'
down_revision: Union[str, Sequence[str], None] = '451a530489f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('is_admin', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('Users', 'credenciais')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('credenciais', sa.VARCHAR(), server_default=sa.text("'User'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('Users', 'is_admin')
    # ### end Alembic commands ###
