"""feat: Adicioando novos campos de data de entrega, corrigindo erros ortograficos.

Revision ID: bf73ea9c46a8
Revises: 7b318d0babc4
Create Date: 2026-09-21 16:52:40.551591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf73ea9c46a8'
down_revision: Union[str, Sequence[str], None] = '7b318d0babc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emprestimos', sa.Column('data_solicitacao', sa.Date(), server_default=sa.text('now()'), nullable=False))
    op.add_column('emprestimos', sa.Column('data_entrega', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emprestimos', 'data_entrega')
    op.drop_column('emprestimos', 'data_solicitacao')
    # ### end Alembic commands ###
